firebase:
 stage: deploy
 before_script:
 - echo -n $GOOGLE_APPLICATION_CREDENTIALS_BASE64 | base64 -d > private-key.json
 - export GOOGLE_APPLICATION_CREDENTIALS="private-key.json"
 - nvm install 18
 - nvm use 18
 - nodejs -v
 script:
 - firebase deploy
