/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Phoenix Limited",
  "tagline": "Pioneering Technology",
  "favicon": "img/favicon.ico",
  "url": "https://wiki.phoenixlimited.net",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://git.phoenixlimited.net/phoenixlimited/wiki-docs/-/tree/main"
        },
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "editUrl": "https://git.phoenixlimited.net/phoenixlimited/wiki-docs/-/tree/main",
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/logo.svg",
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "title": "Phoenix Limited",
      "logo": {
        "alt": "My Site Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "introSidebar",
          "position": "left",
          "label": "Docs"
        },
        {
          "type": "docSidebar",
          "sidebarId": "customerSidebar",
          "position": "left",
          "label": "MSP Customers"
        },
        {
          "type": "docSidebar",
          "sidebarId": "gameSidebar",
          "position": "left",
          "label": "Games"
        },
        {
          "type": "docSidebar",
          "sidebarId": "serverSidebar",
          "position": "left",
          "label": "Server"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "type": "dropdown",
          "position": "right",
          "label": "Customer Portals",
          "items": [
            {
              "label": "SSO Portal",
              "href": "https://auth.phoenixlimited.net"
            },
            {
              "label": "Support",
              "href": "https://support.phoenixlimited.net"
            },
            {
              "label": "Gitlab",
              "href": "https://git.phoenixlimited.net"
            },
            {
              "label": "RMM",
              "href": "https://rmm.phoenixlimited.net"
            },
            {
              "label": "Game Servers",
              "href": "https://panel.phoenixlimited.net"
            },
            {
              "label": "Office",
              "href": "https://office.phoenixlimited.net"
            }
          ]
        },
        {
          "type": "dropdown",
          "position": "right",
          "label": "Quick Links",
          "items": [
            {
              "label": "SSO Portal",
              "href": "https://auth.phoenixlimited.net"
            },
            {
              "label": "Media Server",
              "href": "https://media.phoenixlimited.net"
            },
            {
              "label": "Media Requests",
              "href": "https://request.phoenixlimited.net"
            },
            {
              "label": "Audiobooks & Ebooks",
              "href": "https://books.phoenixlimited.net"
            },
            {
              "label": "Gitlab",
              "href": "https://git.phoenixlimited.net"
            },
            {
              "label": "Uptime",
              "href": "https://uptime.phoenixlimited.net"
            }
          ]
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Docs",
              "to": "/docs/intro"
            },
            {
              "label": " MSP Customers",
              "to": "/docs/customers/intro"
            },
            {
              "label": "Games",
              "to": "/docs/games/intro"
            },
            {
              "label": "Server",
              "to": "/docs/server/login"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Forum",
              "href": "https://forum.phoenixlimited.net"
            },
            {
              "label": "Discord",
              "href": "https://discord.gg/q2GqwHsQeX"
            },
            {
              "label": "Youtube",
              "href": "https://www.youtube.com/@PhoenixLimited"
            }
          ]
        },
        {
          "title": "Social Media",
          "items": [
            {
              "label": "Facebook",
              "href": "https://www.facebook.com/people/Phoenix-Limited/100094090824049/"
            },
            {
              "label": "Instagram",
              "href": "https://www.instagram.com/phoenix_limited/"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/phoenix_lmtd"
            },
            {
              "label": "Blog",
              "to": "/blog"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Terms of Service",
              "href": "/tos"
            },
            {
              "label": "Privacy Policy",
              "href": "/privacy"
            },
            {
              "label": "Uptime",
              "href": "https://uptime.phoenixlimited.net"
            },
            {
              "label": "Git",
              "href": "https://git.phoenixlimited.net/phoenixlimited/wiki-docs/-/tree/main"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Phoenix Limited · Pioneering Technology"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
